### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "newuser@new.com",
    "password": "newuserpass"
}

### Sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "newuser@new.com",
    "password": "newuserpass"
}

### Find a user by id
GET http://localhost:3000/auth/4

### Find all users by email
GET http://localhost:3000/auth?email=newuser@new.com

### Remove a user by id
DELETE http://localhost:3000/auth/2

### Update a user by id
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "password": "tasdasd"
}
